### ISSUE TITLE
error when using tensorboard with crayon: ValueError: The server at 127.0.0.1:8889 does not appear to be up!

### ISSUE THREAD

**Issue by brisker** [longcw/faster_rcnn_pytorch#12]
I just run:
jcc@jcc:~/ground/faster_rcnn_pytorch$ sudo docker pull alband/crayon
[sudo] password for jcc: 
latest: Pulling from alband/crayon
96a1ef3ccac0: Already exists 
2415c9cbee29: Already exists 
285141620f12: Already exists 
cdc8a9d219b0: Already exists 
c6fe6b5c116d: Already exists 
0d3a52687ca5: Already exists 
01fadcdd7016: Already exists 
1c51efe27450: Already exists 
5311a51d16d9: Already exists 
22f8535e4e77: Already exists 
1e29b8d70f1f: Already exists 
49d0cfbbaa13: Already exists 
0cf5e84a5a83: Already exists 
7838253d03e4: Already exists 
ac59d1ca8ffb: Already exists 
967818399371: Already exists 
7b593cbb34a0: Already exists 
fd1d1ebbaede: Already exists 
1ad735e2479d: Already exists 
baae22602681: Already exists 
400ae69c422f: Already exists 
d567ddfceb7d: Already exists 
9a8eff98c4e4: Already exists 
19818a1d0e86: Already exists 
Digest: sha256:33fbe35a1af8b3591e7ec52c57546e34f23813f14e9689cc9d3619c705412c0e
Status: Image is up to date for alband/crayon:latest
jcc@jcc:~/ground/faster_rcnn_pytorch

and then I run "python train.py" and got this error:
voc_2007_trainval gt roidb loaded from /home/jcc/ground/Kaggle/NOAA_SeaLion/faster_rcnn_pytorch/data/cache/voc_2007_trainval_gt_roidb.pkl
Traceback (most recent call last):
  File "train.py", line 96, in <module>
    cc = CrayonClient(hostname='127.0.0.1')
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/pycrayon/crayon.py", line 37, in __init__
    raise ValueError(msg.format(self.hostname, self.port))
ValueError: The server at 127.0.0.1:8889 does not appear to be up!

Anyon helps?

**Comment by acgtyrant** [comment]
Do you run server?

See https://github.com/torrvision/crayon#server-machine-1

**Comment by CuiYiZe** [comment]
i'm meeting the same issue  and try the acgtyrant said but it doesn't work

**Comment by CuiYiZe** [comment]
I rebuild the docker and it does work

**Comment by jtoy** [comment]
lets close this ticket then

**Comment by Hill-Gu** [comment]
Stop the docker, and then start it.

**Comment by mataney** [comment]
Hey, tried to restart the docker.
Didn't help.
Any suggestions?
