### ISSUE TITLE
How to support multigpu?

### ISSUE THREAD

**Issue by philokey** [longcw/faster_rcnn_pytorch#14]
Hello,
How to modify the repo to support multi gpu training?

**Comment by acgtyrant** [comment]
Refer to this: https://github.com/bamos/densenet.pytorch/issues/5#issue-216681444

**Comment by Rizhiy** [comment]
I tried what the comment suggested, it didn't quite work.
I get:
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/rizhiy/miniconda3/envs/rcnn/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/rizhiy/miniconda3/envs/rcnn/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/rizhiy/miniconda3/envs/rcnn/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 22, in _worker
    var_input = var_input[0]
IndexError: invalid index to scalar variable.
```
Same for the other three threads.

I'm new to pytorch can someone help?

Where can I find what the batch size during training is?
