### ISSUE TITLE
Problem: Index tensor must have same dimensions as output tensor

### ISSUE THREAD

**Issue by nku428** [longcw/faster_rcnn_pytorch#30]
Traceback (most recent call last):
  File "train.py", line 154, in <module>
    loss.backward()
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/variable.py", line 152, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/function.py", line 90, in apply
    return self._forward_cls.backward(self, *args)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/_functions/reduce.py", line 176, in backward
    grad_input.scatter_(dim, indices, grad_output)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/variable.py", line 655, in scatter_
    return Scatter.apply(self, dim, index, source, True)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/_functions/tensor.py", line 540, in forward
    return input.scatter_(ctx.dim, index, source)
RuntimeError: Index tensor must have same dimensions as output tensor at /home/pytorch/torch/lib/TH/generic/THTensorMath.c:454

I'm not sure how/why this error occurs, what should i do to make it work. 
Thanks!

**Comment by mbchang** [comment]
I'm having the same problem too.

**Comment by daniilhayrapetyan** [comment]
Got the same issue

**Comment by YykThu** [comment]
got the same problem, any solutions now? thx

**Comment by YykThu** [comment]
ok, I upgrade pytorch to 0.3.1 and problem solved
