### ISSUE TITLE
ValueError: attempt to get argmax of an empty sequence

### ISSUE THREAD

**Issue by Cadene** [longcw/faster_rcnn_pytorch#37]
I am trying to train a model on my custom dataset (formatted like Pascal VOC). The model is training for several iteration and then this error occurs. It is weird to me, because it works perfectly with this repo: https://github.com/amdegroot/ssd.pytorch

```
Traceback (most recent call last):
  File "train.py", line 129, in <module>
    net(im_data, im_info, gt_boxes, gt_ishard, dontcare_areas)
  File "/home/cadene/anaconda3/envs/faster_rcnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cadene/Documents/faster_rcnn_pytorch_python3/faster_rcnn/faster_rcnn.py", line 215, in forward
    features, rois = self.rpn(im_data, im_info, gt_boxes, gt_ishard, dontcare_areas)
  File "/home/cadene/anaconda3/envs/faster_rcnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cadene/Documents/faster_rcnn_pytorch_python3/faster_rcnn/faster_rcnn.py", line 77, in forward
    im_info, self._feat_stride, self.anchor_scales)
  File "/home/cadene/Documents/faster_rcnn_pytorch_python3/faster_rcnn/faster_rcnn.py", line 148, in anchor_target_layer
    anchor_target_layer_py(rpn_cls_score, gt_boxes, gt_ishard, dontcare_areas, im_info, _feat_stride, anchor_scales)
  File "/home/cadene/Documents/faster_rcnn_pytorch_python3/faster_rcnn/rpn_msr/anchor_target_layer.py", line 148, in anchor_target_layer
    gt_argmax_overlaps = overlaps.argmax(axis=0)  # G
ValueError: attempt to get argmax of an empty sequence
```

Obviously the `overlaps` is an empty list, but I can't figure out how to fix this.

**Comment by Cadene** [comment]
I may have found a fix: `_allowed_border = 50`
https://github.com/longcw/faster_rcnn_pytorch/blob/master/faster_rcnn/rpn_msr/anchor_target_layer.py#L69

I hope it will converge nicely.

**Comment by SilencerChen** [comment]
Have you fix this problem? I have the same question and change the _allowed_border from 0 to 50 dose not solve it.Though I use the code in tensorflow. it will be so great if you can tell me how to fix it. Thanks so much.

**Comment by Jongchan** [comment]
In my case, this error occurs when there is no gt box. (I am using a custom dataset)
Removing such samples from the dataset fixed the problem.

**Comment by zqdeepbluesky** [comment]
@SilencerChen @Jongchan 
hi,I met the same problem,did you fix it?can you tell me how to solve it?
thanks so much!!!!

**Comment by qqzeng** [comment]
hi, everybody, I met the same problem, what caused my program occured error is that my DataFrame contains np.NAN. Hope it will help you! :-)
