### ISSUE TITLE
the problem with running demo.py

### ISSUE THREAD

**Issue by pranerd** [longcw/faster_rcnn_pytorch#47]
PC:/media/media_share/linkfile/sceneReco$ python demo.py
Traceback (most recent call last):
File "demo.py", line 3, in  <module>
import torch
File "/home/user/faster_rcnn_pytorch/lfaster_rcnn/network.py", line 1, in <module> 
import torch
File "/home/user/anaconda2/lib/python2.7/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: dlopen: cannot load any more object with static TLS

could you how to do that?

**Comment by MichaelLiang12** [comment]
I can run `demp.py' successfully. But when I try to debug the code, the same error comes.

**Comment by MichaelLiang12** [comment]
Problem alleviated! You can refer to [https://github.com/pytorch/pytorch/issues/2575](https://github.com/pytorch/pytorch/issues/2575) for solutions. Good luck! @pranerd
