### ISSUE TITLE
Meet error when running the demo.py

### ISSUE THREAD

**Issue by qijiezhao** [longcw/faster_rcnn_pytorch#50]
After run **sh make.sh** and download the pretrained VGGnet, I run the demo.py, But I met this following error:

     	[zqj@icst2 faster_rcnn_pytorch-master]$ python demo.py 
	Traceback (most recent call last):
	  File "demo.py", line 46, in <module>
		test()
	  File "demo.py", line 19, in test
		network.load_net(model_file, detector)
	  File "/S2/MI/zqj/temporal_action_localization/faster_rcnn_pytorch-master/faster_rcnn/network.py", line 48, in load_net
		param = torch.from_numpy(np.asarray(h5f[k]))
	  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_objects.c:2846)
	  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_objects.c:2804)
	  File "/opt/anaconda2/lib/python2.7/site-packages/h5py/_hl/group.py", line 169, in __getitem__
		oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
	  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_objects.c:2846)
	  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_objects.c:2804)
	  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/h5o.c:3740)
	KeyError: 'Unable to open object (Bad symbol table node signature)'

what's wrong exactly?

**Comment by qijiezhao** [comment]
I have tried several other .h5 files reading by h5py, however, no error showed. So I bet the given vggnet pretrained model has something error.
Is it a version of python3 file?

**Comment by WeihongM** [comment]
How do you solve this problem?

**Comment by liluxuan1997** [comment]
Have you solved the problem? I met similar one.

**Comment by GloriaZLQ** [comment]
have you solve it？
