### ISSUE TITLE
Please change read.md file and say that the ./make.sh should change arc depending on the gpu used

### ISSUE THREAD

**Issue by avihanai** [longcw/faster_rcnn_pytorch#51]

**Comment by jilner** [comment]
could you help with make.sh

Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 45, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to yo                                                                                                                            ur path, or set $CUDAHOME
Compiling roi pooling kernels by nvcc...
nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
Including CUDA code.
C:\Users\lenovo\Desktop\demo\faster_rcnn_pytorch\faster_rcnn\roi_pooling
generating C:\Users\lenovo\AppData\Local\Temp\tmpcsif72an\_roi_pooling.c
setting the current directory to 'C:\\Users\\lenovo\\AppData\\Local\\Temp\\tmpcs                                                                                                                            if72an'
