### ISSUE TITLE
 error: ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by smallnine9** [longcw/faster_rcnn_pytorch#78]
@longcw 我在./make.sh 的时候，出现了for循环报错，请问作者知道这种情况怎么解决么

**Comment by Luofan-KK** [comment]
I meet the same problem, when it is compiling roi pooling kernels by nvcc. Here is the report 
```
Compiling roi pooling kernels by nvcc...
Including CUDA code.
/home/rootuser/dir1/MSDN/faster_rcnn/roi_pooling
generating /tmp/tmpo5Hmq1/_roi_pooling.c
setting the current directory to '/tmp/tmpo5Hmq1'
running build_ext
building '_roi_pooling' extension
creating home
creating home/rootuser
creating home/rootuser/dir1
creating home/rootuser/dir1/MSDN
creating home/rootuser/dir1/MSDN/faster_rcnn
creating home/rootuser/dir1/MSDN/faster_rcnn/roi_pooling
creating home/rootuser/dir1/MSDN/faster_rcnn/roi_pooling/src
gcc -pthread -B /home/rootuser/anaconda2/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/rootuser/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/rootuser/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/rootuser/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/rootuser/anaconda2/include/python2.7 -c _roi_pooling.c -o ./_roi_pooling.o
In file included from /home/rootuser/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/THVector.h:5:0,
                 from /home/rootuser/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/TH.h:12,
                 from _roi_pooling.c:492:
/home/rootuser/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_polevl’:
/home/rootuser/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:134:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i <= len; i++) {
   ^
/home/rootuser/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:134:3: note: use option -std=c99 or -std=gnu99 to compile your code
/home/rootuser/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_polevlf’:
/home/rootuser/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:142:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i <= len; i++) {
   ^
/home/rootuser/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_trigamma’:
/home/rootuser/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:260:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < 6; ++i) {
   ^
/home/rootuser/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_trigammaf’:
/home/rootuser/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:278:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < 6; ++i) {
   ^
Traceback (most recent call last):
  File "build.py", line 34, in <module>
    ffi.build()
  File "/home/rootuser/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/rootuser/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/rootuser/anaconda2/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/rootuser/anaconda2/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/rootuser/anaconda2/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/rootuser/anaconda2/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
```
