### ISSUE TITLE
make.sh error

### ISSUE THREAD

**Issue by putama** [longcw/faster_rcnn_pytorch#8]
Hi! I encounter an error when I tried to run make.sh file. It says:
`gcc: error: /home/putama/Documents/faster_rcnn_pytorch/faster_rcnn/roi_pooling/src/cuda/roi_pooling.cu.o: No such file or directory
Traceback (most recent call last):
  File "build.py", line 34, in <module>
    ffi.build()
  File "/home/putama/PutamaLab/anaconda/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 164, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/putama/PutamaLab/anaconda/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 100, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/putama/PutamaLab/anaconda/lib/python2.7/site-packages/cffi/api.py", line 672, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/putama/PutamaLab/anaconda/lib/python2.7/site-packages/cffi/recompiler.py", line 1475, in recompile
    compiler_verbose, debug)
  File "/home/putama/PutamaLab/anaconda/lib/python2.7/site-packages/cffi/ffiplatform.py", line 29, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/putama/PutamaLab/anaconda/lib/python2.7/site-packages/cffi/ffiplatform.py", line 65, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.ffiplatform.VerificationError: LinkError: command 'gcc' failed with exit status 1
`
Do you have any idea what's happening? Thanks

**Comment by thisismohitgupta** [comment]
error: /home/Ubuntu/Developer/fasterrcnn/faster_rcnn_pytorch-master/faster_rcnn/roi_pooling/src/cuda/roi_pooling.cu.o: No such file or directory

**Comment by putama** [comment]
Apparently, this happened because I haven't installed nvcc. What an ignorant mistake. Sorry!
