### ISSUE TITLE
./make.sh

### ISSUE THREAD

**Issue by jilner** [longcw/faster_rcnn_pytorch#81]
when I run  ./make.sh   there were 3  traceback
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 45, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to yo                                                                                                                            ur path, or set $CUDAHOME
Compiling roi pooling kernels by nvcc...
nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
Including CUDA code.
C:\Users\lenovo\Desktop\demo\faster_rcnn_pytorch\faster_rcnn\roi_pooling
generating C:\Users\lenovo\AppData\Local\Temp\tmpcsif72an\_roi_pooling.c
setting the current directory to 'C:\\Users\\lenovo\\AppData\\Local\\Temp\\tmpcs                                                                                                                            if72an'
running build_ext
building '_roi_pooling' extension
creating Release
creating Release\Users
creating Release\Users\lenovo
creating Release\Users\lenovo\Desktop
creating Release\Users\lenovo\Desktop\demo
creating Release\Users\lenovo\Desktop\demo\faster_rcnn_pytorch
creating Release\Users\lenovo\Desktop\demo\faster_rcnn_pytorch\faster_rcnn
creating Release\Users\lenovo\Desktop\demo\faster_rcnn_pytorch\faster_rcnn\roi_p                                                                                                                            ooling
creating Release\Users\lenovo\Desktop\demo\faster_rcnn_pytorch\faster_rcnn\roi_p                                                                                                                            ooling\src
e:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.1                                                                                                                            5.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWITH_CUDA -                                                                                                                            IC:\Users\lenovo\Anaconda3\lib\site-packages\torch\utils\ffi\..\..\lib\include -                                                                                                                            IC:\Users\lenovo\Anaconda3\lib\site-packages\torch\utils\ffi\..\..\lib\include\T                                                                                                                            H -IC:\Users\lenovo\Anaconda3\lib\site-packages\torch\utils\ffi\..\..\lib\includ                                                                                                                            e\THC "-IC:\Program Files\NVIDIA Corporation\NvToolsExt\/include" -IC:\Users\len                                                                                                                            ovo\Anaconda3\include -IC:\Users\lenovo\Anaconda3\include "-Ie:\Program Files (x                                                                                                                            86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\ATLMFC\incl                                                                                                                            ude" "-Ie:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\M                                                                                                                            SVC\14.15.26726\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\i                                                                                                                            nclude\um" "-IE:\Windows Kits\10\include\10.0.17134.0\ucrt" "-IE:\Windows Kits\1                                                                                                                            0\include\10.0.17134.0\shared" "-IE:\Windows Kits\10\include\10.0.17134.0\um" "-                                                                                                                            IE:\Windows Kits\10\include\10.0.17134.0\winrt" "-IE:\Windows Kits\10\include\10                                                                                                                            .0.17134.0\cppwinrt" /Tc_roi_pooling.c /Fo.\Release\_roi_pooling.obj
_roi_pooling.c
c:\users\lenovo\anaconda3\lib\site-packages\torch\lib\include\thc\THCGeneral.h(1                                                                                                                            2): fatal error C1083: ▒޷▒▒򿪰▒▒▒▒ļ▒: ▒▒cuda.h▒▒: No such file or directory
Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\lib\distutils\_msvccompiler.py", line 423, in                                                                                                                             compile
    self.spawn(args)
  File "C:\Users\lenovo\Anaconda3\lib\distutils\_msvccompiler.py", line 542, in                                                                                                                             spawn
    return super().spawn(cmd)
  File "C:\Users\lenovo\Anaconda3\lib\distutils\ccompiler.py", line 909, in spaw                                                                                                                            n
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Users\lenovo\Anaconda3\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\Users\lenovo\Anaconda3\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'e:\\Program Files (x86)\\Microsoft                                                                                                                             Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64                                                                                                                            \\cl.exe' failed with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\cffi\ffiplatform.py", line 5                                                                                                                            1, in _build
    dist.run_command('build_ext')
  File "C:\Users\lenovo\Anaconda3\lib\distutils\dist.py", line 974, in run_comma                                                                                                                            nd
    cmd_obj.run()
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\setuptools\command\build_ext                                                                                                                            .py", line 78, in run
    _build_ext.run(self)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\Cython\Distutils\old_build_e                                                                                                                            xt.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\lenovo\Anaconda3\lib\distutils\command\build_ext.py", line 339,                                                                                                                             in run
    self.build_extensions()
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\Cython\Distutils\old_build_e                                                                                                                            xt.py", line 194, in build_extensions
    self.build_extension(ext)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\setuptools\command\build_ext                                                                                                                            .py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\lenovo\Anaconda3\lib\distutils\command\build_ext.py", line 533,                                                                                                                             in build_extension
    depends=ext.depends)
  File "C:\Users\lenovo\Anaconda3\lib\distutils\_msvccompiler.py", line 425, in                                                                                                                             compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'e:\\Program Files (x86)\\Microsoft Visua                                                                                                                            l Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.e                                                                                                                            xe' failed with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 34, in <module>
    ffi.build()
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\torch\utils\ffi\__init__.py"                                                                                                                            , line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\torch\utils\ffi\__init__.py"                                                                                                                            , line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\cffi\api.py", line 697, in c                                                                                                                            ompile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\cffi\recompiler.py", line 15                                                                                                                            20, in recompile
    compiler_verbose, debug)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\cffi\ffiplatform.py", line 2                                                                                                                            2, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\cffi\ffiplatform.py", line 5                                                                                                                            8, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'e:\\Program Files (x86)\\Mi                                                                                                                            crosoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX

**Comment by luminous1004** [comment]
Did you solve your problem?i've got the same situation.
