### ISSUE TITLE
TypeError: dist must be a Distribution instance

### ISSUE THREAD

**Issue by LJ1234com** [longcw/faster_rcnn_pytorch#95]
‘ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.’ was reported when executing 'python3 build.py'. Then i fixed this problem using the link https://blog.csdn.net/ShuqiaoS/article/details/88420326

But a new error occured, 
Traceback (most recent call last):
  File "/home/lijian/study/cv/faster_rcnn_pytorch/faster_rcnn_pytorch/faster_rcnn/roi_pooling/build.py", line 31, in <module>
    extra_objects=extra_objects
  File "/home/lijian/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 228, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/home/lijian/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in __init__
    _Command.__init__(self, dist)
  File "/home/lijian/anaconda3/lib/python3.7/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance

**Comment by dongxijia** [comment]
I got the same problem, did you fix it ?

**Comment by dongxijia** [comment]
I find it because the vesion the torch is too high. And I change 1.01 to 0.4.1, it success.

**Comment by Don98** [comment]
It is same as me , but I don't want to change the torch from 1.01 to 0.4.1 reason why I use this rep is it support the torhc 1.0.1 !

**Comment by henbucuoshanghai** [comment]
the same  error
_Command.init(self, dist)
File "/home/lijian/anaconda3/lib/python3.7/distutils/cmd.py", line 57, in init
raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance

**Comment by henbucuoshanghai** [comment]
how  to slove it???
